/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kencode.project.view;
    
import com.kencode.project.controller.ControllerFactory;
import com.kencode.project.controller.custom.GoodsController;
import com.kencode.project.controller.custom.IdController;
import com.kencode.project.controller.custom.OrdersController;
import com.kencode.project.controller.custom.ValidationController;
import com.kencode.project.dao.db.ConnectionFactory;
import com.kencode.project.dto.GoodsDTO;
import com.kencode.project.dto.OrderDetailDTO;
import com.kencode.project.dto.OrdersDTO;
import com.kencode.project.dto.ServiceDTO;
import java.awt.Container;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Sandun Dilhan
 */
public class GinPanel extends javax.swing.JPanel {
    private int grandAmount=0;
    private GoodsController ctrlGoods;
    private IdController ctrlId;
    private OrdersController ctrlOrders;
    private ValidationController ctrlValidation;
    private Connection conn;
    /**
     * Creates new form GinPanel
     */
    public GinPanel() {
        initComponents();
        setSize(1366,604);
        
        txtDate.setEditable(false);
        txtOrderID.setEditable(false);
        txtItemCode.setEditable(false);
        txtSid.setEditable(false);
        txtAmount.setEditable(false);
        
        ctrlOrders=(OrdersController) ControllerFactory.getInstance().getControllerTypes(ControllerFactory.ControllerTypes.ORDERS);
        ctrlGoods=(GoodsController) ControllerFactory.getInstance().getControllerTypes(ControllerFactory.ControllerTypes.GOODS);
        ctrlId=(IdController) ControllerFactory.getInstance().getControllerTypes(ControllerFactory.ControllerTypes.IDGEN);
        ctrlValidation=(ValidationController) ControllerFactory.getInstance().getControllerTypes(ControllerFactory.ControllerTypes.VALIDATION);
        conn=ConnectionFactory.getInstance().getConnection();
        
        loadDate();
        loadDescription();
        generateOID();
        generateSID();
        
        AutoCompleteDecorator.decorate(cmbDescription);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbDescription = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSPrice = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSremove = new javax.swing.JButton();
        btnSadd = new javax.swing.JButton();
        txtOrderID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Order Id");

        txtSid.setBackground(new java.awt.Color(153, 153, 153));
        txtSid.setForeground(new java.awt.Color(255, 255, 255));
        txtSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date");

        txtDate.setBackground(new java.awt.Color(153, 153, 153));
        txtDate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Description");

        cmbDescription.setFont(new java.awt.Font("FMAbhaya", 0, 18)); // NOI18N
        cmbDescription.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDescriptionItemStateChanged(evt);
            }
        });
        cmbDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDescriptionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Item Code");

        txtItemCode.setBackground(new java.awt.Color(153, 153, 153));
        txtItemCode.setForeground(new java.awt.Color(255, 255, 255));
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("QTY");

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Unit Price");

        txtUnitPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnitPriceMouseClicked(evt);
            }
        });
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setText("REMOVE");
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("SID");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Service Description");

        txtDescription.setFont(new java.awt.Font("FMAbhaya", 0, 18)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Price");

        txtSPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPriceActionPerformed(evt);
            }
        });

        btnSremove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSremove.setText("REMOVE");
        btnSremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSremoveMouseClicked(evt);
            }
        });
        btnSremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSremoveActionPerformed(evt);
            }
        });

        btnSadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSadd.setText("ADD");
        btnSadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaddMouseClicked(evt);
            }
        });

        txtOrderID.setEditable(false);
        txtOrderID.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(646, 646, 646)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSadd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSremove, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cmbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOrderID))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSremove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        tblOrder.setFont(new java.awt.Font("FMAbhaya", 0, 18)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Description", "QTY", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setMinWidth(0);
            tblOrder.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblOrder.getColumnModel().getColumn(0).setMaxWidth(0);
            tblOrder.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblOrder.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Grand Total       Rs.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 11, 126, 30));

        txtAmount.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1221, 12, 135, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE & PRINT");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1221, 48, -1, 34));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 127, 34));

        tblService.setFont(new java.awt.Font("FMAbhaya", 0, 18)); // NOI18N
        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Service Description", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblService);
        if (tblService.getColumnModel().getColumnCount() > 0) {
            tblService.getColumnModel().getColumn(0).setMinWidth(0);
            tblService.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblService.getColumnModel().getColumn(0).setMaxWidth(0);
            tblService.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblService.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSidActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        SearchOrderFrame order=new SearchOrderFrame();
        order.setVisible(true);
    }//GEN-LAST:event_btnSearchMouseClicked

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        txtSPrice.requestFocus();
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        try {
            if(ctrlValidation.setNumberFormat(txtUnitPrice.getText())){
                grandAmountAction();
                orderClearText();
            }else{
                JOptionPane.showMessageDialog(this,"You can use only numbers!");
                txtUnitPrice.setText("");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtUnitPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnitPriceMouseClicked
        
    }//GEN-LAST:event_txtUnitPriceMouseClicked

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        
        try {
            if(ctrlValidation.setNumberFormat(txtUnitPrice.getText())){
                grandAmountAction();
                orderClearText();
            }else{
                JOptionPane.showMessageDialog(this,"You can use only numbers!"); 
                txtUnitPrice.setText("");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtSPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSPriceActionPerformed
        
        try {
            if(ctrlValidation.setNumberFormat(txtSPrice.getText())){
                serviceGrandTotalActoin();
                serviceClearText();
                generateContinuesSID();
            }else{ 
                JOptionPane.showMessageDialog(this,"You can use only numbers!");
                txtSPrice.setText("");
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSPriceActionPerformed

    private void btnSaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaddMouseClicked
        
        try {
            if(ctrlValidation.setNumberFormat(txtSPrice.getText())){
                serviceGrandTotalActoin();
                serviceClearText();
            }else{
                JOptionPane.showMessageDialog(this,"You can use only numbers!");
                txtSPrice.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSaddMouseClicked

    private void cmbDescriptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDescriptionItemStateChanged
       String desc=(String) cmbDescription.getSelectedItem();
        try {
            GoodsDTO goods=ctrlGoods.search(desc);
            txtItemCode.setText(goods.getGid());
            txtUnitPrice.setText(Integer.toString(goods.getPrice()));
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbDescriptionItemStateChanged

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        
        try {
            DecimalFormat df =new DecimalFormat("#,###.00");
            df.setMaximumFractionDigits(2);
            
            DecimalFormat dfd =new DecimalFormat("#");
            dfd.setMaximumFractionDigits(2);
            
            DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
            int amount=Integer.parseInt(dfd.format(df.parse((String) dtm.getValueAt(tblOrder.getSelectedRow(),4))));
            dtm.removeRow(tblOrder.getSelectedRow());
            grandAmount=grandAmount-amount;
            txtAmount.setText(df.format(grandAmount));
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnSremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSremoveMouseClicked
       
        try {
            DecimalFormat df =new DecimalFormat("#,###.00");
            df.setMaximumFractionDigits(2);
            
            DecimalFormat dfd =new DecimalFormat("#");
            dfd.setMaximumFractionDigits(2);
            
            
            DefaultTableModel dtm=(DefaultTableModel)tblService.getModel();
            int price=Integer.parseInt(dfd.format(df.parse(((String)dtm.getValueAt(tblService.getSelectedRow(),2)) )));
            dtm.removeRow(tblService.getSelectedRow());
            grandAmount=grandAmount-price;
            txtAmount.setText(df.format(grandAmount));
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSremoveMouseClicked

    private void cmbDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDescriptionActionPerformed
        txtQty.requestFocus();
    }//GEN-LAST:event_cmbDescriptionActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
       
        try {
            String text=txtQty.getText();
            if(!ctrlValidation.setNumberFormat(text)){
                JOptionPane.showMessageDialog(this,"You can type only numbers!");
                txtQty.setText("");
            }else{
                txtUnitPrice.requestFocus();
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        
        try {
            DecimalFormat df=new DecimalFormat("#,###.00");
            df.setMaximumFractionDigits(2);
            
            DecimalFormat dfd=new DecimalFormat("#");
            dfd.setMaximumFractionDigits(2);
            
            DefaultTableModel dtmOrder=(DefaultTableModel) tblOrder.getModel();
            DefaultTableModel dtmService=(DefaultTableModel) tblService.getModel();
            
            if(dtmOrder.getRowCount()==0 && dtmService.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"You have an error!"); 
            }else{
                OrdersDTO o=new OrdersDTO(txtOrderID.getText(), grandAmount, txtDate.getText());
                ArrayList<OrderDetailDTO> olist=new ArrayList<>();
                ArrayList<ServiceDTO> slist=new ArrayList<>();
                int count=0;
                for(int i=0;i<dtmOrder.getRowCount();i++){
                    count++;
                    System.out.println(txtOrderID.getText());
                    OrderDetailDTO od=new OrderDetailDTO(txtOrderID.getText(),(String)dtmOrder.getValueAt(i, 0), (int) dtmOrder.getValueAt(i, 2),count);
                    olist.add(od);
                }
                for(int i=0;i<dtmService.getRowCount();i++){
                    ServiceDTO service=new ServiceDTO((String) dtmService.getValueAt(i, 0),txtOrderID.getText(), (String) dtmService.getValueAt(i, 1), Integer.parseInt(dfd.format(df.parse((String)dtmService.getValueAt(i, 2)))) );
                    slist.add(service);
                }
                
                if(dtmService.getRowCount()==0){
                    
                    boolean isAdd=ctrlOrders.add(o, olist);
                    if(isAdd){
                         JOptionPane.showMessageDialog(this,"Order Success!");
                         jasperReportOrderBill1();
                         txtAmount.setText("");
                         grandAmount=0;
                         generateOID();
                    }else{
                         JOptionPane.showMessageDialog(this,"Order Failed");
                         
                    }
                }else{
                    boolean isAdd=ctrlOrders.add(o, olist, slist);
                    if(isAdd){
                         JOptionPane.showMessageDialog(this,"Order Success!");
                        jasperReportOrderBill3();
                        jasperReportOrderBill2();
                        txtAmount.setText("");
                        grandAmount=0;
                        generateOID();
                    }else{
                         JOptionPane.showMessageDialog(this,"Order Failed");  
                    }
                }
            }
            
            dtmOrder.setRowCount(0);
            dtmService.setRowCount(0);
            
        } catch (Exception ex) {
          Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);  
          JOptionPane.showMessageDialog(this,"You have an error!");  
        }
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSremoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSremoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSadd;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSremove;
    private javax.swing.JComboBox cmbDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSPrice;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
    private void grandAmountAction(){
        DecimalFormat df=new DecimalFormat("#,###.00");
        df.setMaximumFractionDigits(2);
        DecimalFormat dfd=new DecimalFormat("#");
        dfd.setMaximumFractionDigits(2);
        try{
            String code=txtItemCode.getText();
            String description=(String) cmbDescription.getSelectedItem();
            int orderQty=Integer.parseInt(txtQty.getText());
            int unitprice=Integer.parseInt(txtUnitPrice.getText());
            String unitPrice=df.format(unitprice);

            DefaultTableModel dtm=(DefaultTableModel) tblOrder.getModel();

            for(int i=0;i<dtm.getRowCount();i++){
                String itemCode=(String) dtm.getValueAt(i, 0);
                String desc=(String) dtm.getValueAt(i, 1);
                if(itemCode.equals(code) && desc.equals(description)){

                    int qty=(int) dtm.getValueAt(i, 2);
                    int tempTotal=Integer.parseInt(dfd.format(df.parse((String) dtm.getValueAt(i, 4))));
                    orderQty=orderQty+qty;
                    grandAmount=grandAmount-tempTotal;
                    txtAmount.setText(""+grandAmount);
                    dtm.removeRow(i);
                }
            }
            int grandTot=orderQty*(unitprice);
            grandAmount=grandAmount+grandTot;
            txtAmount.setText(df.format(grandAmount));

            String grandTotal=df.format(grandTot);
            Object[] rowData={code,description,orderQty,unitPrice,grandTotal};
            dtm.addRow(rowData);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"You missed some fields!");  
        }
    }
    private void serviceGrandTotalActoin(){
        
        try{
            DecimalFormat df=new DecimalFormat("#,###.00");
            df.setMaximumFractionDigits(2);
            DecimalFormat dfd=new DecimalFormat("#");
            dfd.setMaximumFractionDigits(2);

            String sID=txtSid.getText();
            String sDescription=txtDescription.getText();
            int sPrice=Integer.parseInt(txtSPrice.getText());

            DefaultTableModel dtm=(DefaultTableModel) tblService.getModel();

            grandAmount=grandAmount+sPrice;
            txtAmount.setText(df.format(grandAmount));

            String grandTotal=df.format(sPrice);
            Object[]rowData={sID,sDescription,grandTotal};
            dtm.addRow(rowData);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"You missed some fields");  
        }
    }
    private void serviceClearText(){
       
        txtDescription.setText("");
        txtSPrice.setText("");
    }
     private void orderClearText(){
        txtQty.setText("");
    }
     
    private void loadDate(){
        Date d1=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        String formatDate=df.format(d1);
        txtDate.setText(formatDate);
    }
    private void loadDescription(){
        try {
            ArrayList<GoodsDTO>goodsList=ctrlGoods.getAll();
            for (int i=0;i<goodsList.size();i++) {
                GoodsDTO goods=goodsList.get(i);
                cmbDescription.addItem(goods.getGood_name());
            }
        } catch (Exception ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generateOID() {
        
        try {
            txtOrderID.setText(ctrlId.getNewID("orders","oid","OD",3));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void generateSID() {
        
        try {
            txtSid.setText(ctrlId.getNewID("service","sid","SV",3));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void generateContinuesSID(){
        
        String batch=txtSid.getText();
        
        char[] batchArr=batch.toCharArray();

        if(batchArr[2]=='0' && batchArr[3]=='0' && batchArr[4]=='0' && batchArr[5]=='9'){
            txtSid.setText("SV0010");
            return;
        }else if(batchArr[2]=='0' && batchArr[3]=='0' && batchArr[4]=='9' && batchArr[5]=='9'){
            txtSid.setText("SV0100");
            return;
        }else if(batchArr[2]=='0' && batchArr[3]=='9' && batchArr[4]=='9' && batchArr[5]=='9' && batchArr.length==6){
            txtSid.setText("SV1000");
            return;
        }else if(batchArr[2]=='9' && batchArr[3]=='9' && batchArr[4]=='9' && batchArr[5]=='9' && batchArr.length==6){
            txtSid.setText("SV10000");
            return;
        }else if(batchArr[2]=='9' && batchArr[3]=='9' && batchArr[4]=='9' && batchArr[5]=='9' && batchArr[6]=='9' && batchArr.length==7){
            txtSid.setText("SV100000");
            return;
        }else if(batchArr[2]=='9' && batchArr[3]=='9' && batchArr[4]=='9' && batchArr[5]=='9' && batchArr[6]=='9' && batchArr[7]=='9' && batchArr.length==8){
            txtSid.setText("SV1000000");
            return;
        }
        if(batchArr[2]=='0' && batchArr[3]=='0' && batchArr[4]=='0' &&  batchArr[5]<'9'){

           int batchNo=Integer.parseInt(batchArr[5]+"")+1;
           txtSid.setText("SV000"+Integer.toString(batchNo));

        }else{
            String batchNo="";
            for(int i=2;i<batchArr.length;i++){
                batchNo=batchNo+(batchArr[i]+"");
            }
            int nextNo=Integer.parseInt(batchNo)+1;

            char[] num=Integer.toString(nextNo).toCharArray();
            if(num.length==2){

                txtSid.setText("SV00"+nextNo);
            }else if(num.length==3){

                txtSid.setText("SV0"+nextNo);
            }else if(num.length>3){

                txtSid.setText("SV"+nextNo);
            }
        }
        
    }private void jasperReportOrderBill1(){
         try {
            JasperReport main=(JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/com/kencode/project/controller/jasper/reports/Gin_order.jasper"));
            
            HashMap<String,Object> parameters=new HashMap<>();
            System.out.println(txtOrderID.getText());
            parameters.put("orderId",txtOrderID.getText());

            JasperPrint fill=JasperFillManager.fillReport(main, parameters,conn);
            
            JasperViewer view=new JasperViewer(fill);
             JDialog dialog=new JDialog();
             Container container=view.getContentPane();
             dialog.setContentPane(container);
             dialog.setSize(view.getSize());
             dialog.setVisible(true);

            } catch (JRException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void jasperReportOrderBill2(){
         try {
            JasperReport main=(JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/com/kencode/project/controller/jasper/reports/Gin_order.jasper"));
            
            HashMap<String,Object> parameters=new HashMap<>();
            System.out.println(txtOrderID.getText());
            parameters.put("orderId",txtOrderID.getText());

            JasperPrint fill=JasperFillManager.fillReport(main, parameters,conn);
            
             JasperViewer view=new JasperViewer(fill);
             JDialog dialog=new JDialog();
             Container container=view.getContentPane();
             dialog.setContentPane(container);
             dialog.setSize(view.getSize());
             dialog.setVisible(true);
           

            } catch (JRException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void jasperReportOrderBill3(){
         try {
            JasperReport main=(JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/com/kencode/project/controller/jasper/reports/Gin_service.jasper"));
            
            HashMap<String,Object> parameters=new HashMap<>();
            //System.out.println(txtOrderID.getText());
            parameters.put("order_Id",txtOrderID.getText());

            JasperPrint fill=JasperFillManager.fillReport(main, parameters,conn);
            
             JasperViewer view=new JasperViewer(fill);
             JDialog dialog=new JDialog();
             Container container=view.getContentPane();
             dialog.setContentPane(container);
             dialog.setSize(view.getSize());
             dialog.setVisible(true);
           
            } catch (JRException ex) {
            Logger.getLogger(GinPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}
